### ISSUE TITLE
MightyString 0.1.6 breaks Rails Cookies

### ISSUE THREAD

**Issue by danielpclark** [danielpclark/MightyString#3]
ArgumentError - wrong number of arguments (1 for 0):
      actionpack (4.1.6) lib/action_dispatch/middleware/cookies.rb:566:in `call'
      activerecord (4.1.6) lib/active_record/query_cache.rb:36:in `call'
      activerecord (4.1.6) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
      activerecord (4.1.6) lib/active_record/migration.rb:380:in `call'
      actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
      activesupport (4.1.6) lib/active_support/callbacks.rb:82:in `run_callbacks'
      actionpack (4.1.6) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
      actionpack (4.1.6) lib/action_dispatch/middleware/reloader.rb:73:in `call'
      actionpack (4.1.6) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
      better_errors (2.0.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
      better_errors (2.0.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
      better_errors (2.0.0) lib/better_errors/middleware.rb:57:in `call'
      actionpack (4.1.6) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
      actionpack (4.1.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
      railties (4.1.6) lib/rails/rack/logger.rb:38:in `call_app'
      railties (4.1.6) lib/rails/rack/logger.rb:20:in `block in call'
      activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
      activesupport (4.1.6) lib/active_support/tagged_logging.rb:26:in `tagged'
      activesupport (4.1.6) lib/active_support/tagged_logging.rb:68:in `tagged'
      railties (4.1.6) lib/rails/rack/logger.rb:20:in `call'
      quiet_assets (1.0.3) lib/quiet_assets.rb:23:in `call_with_quiet_assets'
      actionpack (4.1.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
      rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
      rack (1.5.2) lib/rack/runtime.rb:17:in `call'
      activesupport (4.1.6) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
      rack (1.5.2) lib/rack/lock.rb:17:in `call'
      actionpack (4.1.6) lib/action_dispatch/middleware/static.rb:64:in `call'
      rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
      railties (4.1.6) lib/rails/engine.rb:514:in `call'
      railties (4.1.6) lib/rails/application.rb:144:in `call'
      rack (1.5.2) lib/rack/lock.rb:17:in `call'
      rack (1.5.2) lib/rack/content_length.rb:14:in `call'
      rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
      /home/user/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/webrick/httpserver.rb:138:in `service'
      /home/user/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/webrick/httpserver.rb:94:in `run'
      /home/user/.rvm/rubies/ruby-2.2.0-preview1/lib/ruby/2.2.0/webrick/server.rb:320:in `block in start_thread'

The body local var comes back as a list of 10,551 individual charcaters.  Excerpt:

    ["<", "!", "D", "O", "C", "T", "Y", "P", "E", " ", "h", "t", "m", "l", ">", "\n", "<", "h", "t", "m", "l", ">",
    "\n", "<", "h", "e", "a", "d", ">", "\n", " ", " ", "<", "m", "e", "t", "a", " ", "n", "a", "m", "e", "=",
    "\"", "v", "i", "e", "w", "p", "o", "r", "t", "\"", " ", "c", "o", "n", "t", "e", "n", "t", "=", "\"", "w",
    "i", "d", "t", "h", "=", "d", "e", "v", "i", "c", "e", "-", "w", "i", "d", "t", "h", ",", " ", "i", "n", "i",
    "t", "i", "a", "l", "-", "s", "c", "a", "l", "e", "=", "1", ".", "0", "\"", ">", "\n", " ", " ", "<", "t", "i",
    "t", "l", "e", ">",
    ...
    "<", "/", "d", "i", "v", ">", "\n", " ", " ", " ", " ", " ", " ", " ", " ", "<", "d", "i", "v", " ", "c", "l",
    "a", "s", "s", "=", "\"", "c", "o", "l", "-", "m", "d", "-", "5", "\"", ">", "\n", " ", " ", " ", " ", " ", "
    ", " ", " ", " ", " ", "\n", " ", " ", " ", " ", " ", " ", " ", " ", "<", "/", "d", "i", "v", ">", "\n", " ",
    " ", " ", " ", " ", " ", "<", "/", "d", "i", "v", ">", "\n", " ", " ", " ", " ", "<", "/", "d", "i", "v", ">",
    "\n", "<", "/", "m", "a", "i", "n", ">", "\n", "<", "/", "b", "o", "d", "y", ">", "\n", "<", "/", "h", "t",
    "m", "l", ">", "\n"]

**Comment by danielpclark** [comment]
Code not in use.
